#!/bin/bash

if [  $# -eq 0 ]; then
    exit
else
    echo "----split----" >> ~/.word/vocabulary.txt
    trans "$*" | tee -a ~/.word/vocabulary.txt
    curdir=$(pwd)
    cd ~/samba/
    trans -no-translate -download-audio "$*"
    cd $curdir
fi
